name = "MintsMakieRecipes"
uuid = "6ebddb0b-cb6d-4cb8-921a-b084ea45d677"
authors = ["John Waczak <john.louis.waczak@gmail.com>"]
version = "0.1.0"

[deps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
RelocatableFolders = "05181044-ff0b-4ac5-8273-598c1e38db00"

[compat]
julia = "1.9"
Makie = "0.19.8"
RelocatableFolders = "1.0.0"


[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
